# netty configuration
netty:
  port: 10100
  threads:
    worker: 4
    acceptor: 2
  backlog: 100
  report:
    use : true
    interval: 60000

# logging level
logging:
  level:
    org:
      springframework: info
    io:
      netty: debug
    com:
      gompang: info
