// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

public final class AuthResult {
  private AuthResult() { }
  public static final short FAIL = 0;
  public static final short INVALID_TOKEN = 1;
  public static final short SUCCESS = 2;

  public static final String[] names = { "FAIL", "INVALID_TOKEN", "SUCCESS", };

  public static String name(int e) { return names[e]; }
}

