// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

public final class CommonResult {
  private CommonResult() { }
  public static final short FAIL = 0;
  public static final short SUCCESS = 1;

  public static final String[] names = { "FAIL", "SUCCESS", };

  public static String name(int e) { return names[e]; }
}

