// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class DeviceRegisterMsg extends Table {
  public static DeviceRegisterMsg getRootAsDeviceRegisterMsg(ByteBuffer _bb) { return getRootAsDeviceRegisterMsg(_bb, new DeviceRegisterMsg()); }
  public static DeviceRegisterMsg getRootAsDeviceRegisterMsg(ByteBuffer _bb, DeviceRegisterMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public DeviceRegisterMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String deviceId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer deviceIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer deviceIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String userId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer userIdInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createDeviceRegisterMsg(FlatBufferBuilder builder,
      int deviceIdOffset,
      int userIdOffset) {
    builder.startObject(2);
    DeviceRegisterMsg.addUserId(builder, userIdOffset);
    DeviceRegisterMsg.addDeviceId(builder, deviceIdOffset);
    return DeviceRegisterMsg.endDeviceRegisterMsg(builder);
  }

  public static void startDeviceRegisterMsg(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addDeviceId(FlatBufferBuilder builder, int deviceIdOffset) { builder.addOffset(0, deviceIdOffset, 0); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(1, userIdOffset, 0); }
  public static int endDeviceRegisterMsg(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

