// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Login extends Table {
  public static Login getRootAsLogin(ByteBuffer _bb) { return getRootAsLogin(_bb, new Login()); }
  public static Login getRootAsLogin(ByteBuffer _bb, Login obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Login __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createLogin(FlatBufferBuilder builder,
      int idOffset) {
    builder.startObject(1);
    Login.addId(builder, idOffset);
    return Login.endLogin(builder);
  }

  public static void startLogin(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static int endLogin(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

