// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Logout extends Table {
  public static Logout getRootAsLogout(ByteBuffer _bb) { return getRootAsLogout(_bb, new Logout()); }
  public static Logout getRootAsLogout(ByteBuffer _bb, Logout obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Logout __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String id() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer idAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer idInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createLogout(FlatBufferBuilder builder,
      int idOffset) {
    builder.startObject(1);
    Logout.addId(builder, idOffset);
    return Logout.endLogout(builder);
  }

  public static void startLogout(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addId(FlatBufferBuilder builder, int idOffset) { builder.addOffset(0, idOffset, 0); }
  public static int endLogout(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

