// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

public final class PacketType {
  private PacketType() { }
  public static final byte HEART_BEAT = 0;
  public static final byte LOGIN = 1;
  public static final byte LOGOUT = 2;

  public static final String[] names = { "HEART_BEAT", "LOGIN", "LOGOUT", };

  public static String name(int e) { return names[e]; }
}

