// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

public final class PacketType {
  private PacketType() { }
  public static final byte HeartBeat = 0;
  public static final byte Login = 1;
  public static final byte Logout = 2;

  public static final String[] names = { "HeartBeat", "Login", "Logout", };

  public static String name(int e) { return names[e]; }
}

