// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

public final class PacketType {
  private PacketType() { }
  public static final byte HeartBeat = 0;
  public static final byte DeviceRegister = 1;
  public static final byte PlayerLogin = 2;

  public static final String[] names = { "HeartBeat", "DeviceRegister", "PlayerLogin", };

  public static String name(int e) { return names[e]; }
}

