// automatically generated by the FlatBuffers compiler, do not modify

package com.gompang.packet;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class PlayerLoginMsg extends Table {
  public static PlayerLoginMsg getRootAsPlayerLoginMsg(ByteBuffer _bb) { return getRootAsPlayerLoginMsg(_bb, new PlayerLoginMsg()); }
  public static PlayerLoginMsg getRootAsPlayerLoginMsg(ByteBuffer _bb, PlayerLoginMsg obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public PlayerLoginMsg __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String userId() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer userIdAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String deviceId() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer deviceIdAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String token() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tokenAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createPlayerLoginMsg(FlatBufferBuilder builder,
      int userIdOffset,
      int deviceIdOffset,
      int tokenOffset) {
    builder.startObject(3);
    PlayerLoginMsg.addToken(builder, tokenOffset);
    PlayerLoginMsg.addDeviceId(builder, deviceIdOffset);
    PlayerLoginMsg.addUserId(builder, userIdOffset);
    return PlayerLoginMsg.endPlayerLoginMsg(builder);
  }

  public static void startPlayerLoginMsg(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addUserId(FlatBufferBuilder builder, int userIdOffset) { builder.addOffset(0, userIdOffset, 0); }
  public static void addDeviceId(FlatBufferBuilder builder, int deviceIdOffset) { builder.addOffset(1, deviceIdOffset, 0); }
  public static void addToken(FlatBufferBuilder builder, int tokenOffset) { builder.addOffset(2, tokenOffset, 0); }
  public static int endPlayerLoginMsg(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

